- name: Update apt package list
  apt:
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: Restart nginx to apply changes
  service:
    name: nginx
    state: restarted
  notify: Restart Nginx